// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my LV Concierge profile",
  description: "Return the signed-in user's LV Concierge profile (pseudonym, bio, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("pseudonym, bio, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-travel-history.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_travel_history_default = defineTool2({
  name: "list_travel_history",
  title: "List my travel history",
  description: "List the signed-in user's LV Concierge travel history entries, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of trips to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("travel_history").select("*").eq("user_id", ctx.getUserId()).order("travel_date", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-vault-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_vault_posts_default = defineTool3({
  name: "list_vault_posts",
  title: "List Vault posts",
  description: "List recent posts from The Vault, the LV Concierge members' feed.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("vault_posts").select("id, pseudonym, content, destination, image_url, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-vault-post.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_vault_post_default = defineTool4({
  name: "create_vault_post",
  title: "Create a Vault post",
  description: "Publish a new post to The Vault as the signed-in LV Concierge member.",
  inputSchema: {
    content: z3.string().trim().min(1).describe("Post body text."),
    destination: z3.string().trim().optional().describe("Optional destination tag.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, destination }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await supabase.from("profiles").select("pseudonym").eq("user_id", userId).maybeSingle();
    const pseudonym = profile?.pseudonym ?? "Anonymous";
    const { data, error } = await supabase.from("vault_posts").insert({ user_id: userId, pseudonym, content, destination: destination ?? null }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wwgtcvpktisjhalfbjhp";
var mcp_default = defineMcp({
  name: "lv-concierge-mcp",
  title: "LV Concierge",
  version: "0.1.0",
  instructions: "Tools for the LV Concierge ultra-luxury travel app. Read the signed-in member's profile, travel history, and The Vault feed, and publish new Vault posts as that member.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_travel_history_default,
    list_vault_posts_default,
    create_vault_post_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
